artifact_location: file:F:/BROTOTYPE WEEK TASKS/WEEK 49/FER-using-YOLOv11/runs/mlflow/0
creation_time: 1761826021145
experiment_id: '0'
last_update_time: 1761826021145
lifecycle_stage: active
name: Default
